name: Kernel Test
on:
  workflow_dispatch: # Allows manual triggering
jobs:
  build:
    runs-on: [self-hosted, amd64, tiobe, noble]
    steps:
      - name: uname -a
        run: uname -a
      - name: check grub
        run: sudo grep -E "submenu|menuentry" /boot/grub/grub.cfg
